### ISSUE TITLE
Bot API updated in 26 Apr removed service messages about non-bot users join from large groups

### ISSUE THREAD

**Issue by superstaraug** [Hentioe/policr-mini#101]
As Telegram bot API updated in 26th April said "Service messages about non-bot users joining the chat will be soon removed from large groups.  We recommend using the "chat_member" update as a replacement".

It effected the current policr mini bot in "large groups".

To update policr-mini, the bot API 5.1 should be useful.

March 9, 2021
Bot API 5.1
Added two new update types
  Added updates about member status changes in chats, represented by the class ChatMemberUpdated and the fields my_chat_member and chat_member in the Update class. The bot must be an administrator in the chat to receive chat_member updates about other chat members. By default, only my_chat_member updates about the bot itself are received.

**Comment by Hentioe** [comment]
感谢提醒，这个我也看到了。 policr mini 的 bot api 库是自己开发的，不受任何上游的限制。如果我有空，会很快适配最新的 api 变动。Thanks again, for your reminder.

**Comment by Hentioe** [comment]
The phenomenon mentioned in this issue has been resolved.
