### ISSUE TITLE
自定义验证中的「附件组」类型支持

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/policr-mini#108]
可选择添加图片、音频、视频、文档（文件）四种类型作为问题附件，支持多个。支持文字，且文字是必要的。

需要注意的是：
1. 音频和文件类型只能独立作为多个发送，不能与其它类型混用。目前来讲，只允许混发图片和视频。
1. 一个附件组至多允许存在 10 个附件。

当前计划后台设计如下：
1. 在编辑框中输入附件字符串（格式：类型前缀/文件ID），例如 `photo/<文件ID>`。
1. 所有前缀采用 TG 的命名，分别是：`photo` / `audio` / `video` / `document` 。
1. 输入框中高亮文件类型部分，以和文件ID部分明显区分开来。

当前计划 bot 设计如下：
1. 向机器人私聊以上类型的文件，将自动返回文件信息以及文件ID。
2. 向机器人私聊附件字符串，将自动发送相关文件。（注意，必须是附件字符串格式，需要类型前缀）

当文件过大时，返回消息中加入文件太大，可能影响用户验证的提示消息。

**Comment by Hentioe** [comment]
当前的实现有以下差异：

附件组改为单个附件支持，因为 `sendMediaGroup` 方法暂时不支持 `reply_markup` 字段。编辑框中的附件类型没有高亮，暂时不考虑此实现。

目前存在几个后续待做的优化：

1. 部分发送方法没有添加超时重试机制。
1. 部分发送方法不支持 `MarkdownV2` 转 `HTML`。
1. 消息快照中没有存储附件 ID。

**Comment by sam01101** [comment]
@Hentioe .

**Comment by Hentioe** [comment]
上述评论问题已全部解决。
