### ISSUE TITLE
自定义问题标题过长，会导致网页上模拟预览发生错误

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/policr-mini#110]
如果标题太长（例如几十个字），消息气泡就会太宽，头像尺寸被挤压到非常小。正确的情况应该是消息气泡总宽度应该有一个上限，且不会造成和头像的拥挤。

**Comment by Emojigit** [comment]
![圖片](https://user-images.githubusercontent.com/55009343/121805897-dd42fd80-cc7f-11eb-8989-c53ec6c875f3.png)
沒有問題啊

**Comment by Hentioe** [comment]
> ![圖片](https://user-images.githubusercontent.com/55009343/121805897-dd42fd80-cc7f-11eb-8989-c53ec6c875f3.png)
> 沒有問題啊

点编辑，下面有一个模拟的验证消息预览。我指的这个，不是说列表显示有问题。
