### ISSUE TITLE
如何设置才能实现验证方式为自定义时，必须连续答对多个定义的问题才能通过验证进群？

### ISSUE THREAD

**Issue by toaoman** [Hentioe/policr-mini#138]
如何设置才能实现验证方式为自定义时，必须连续答对多个定义的问题才能通过验证进群？

目前在使用https://t.me/policr_mini_bot 测试的时候，发现可以设置验证方式为自定义，并且定义了多个问题，但是在设置好问题后，在入群测试时发现只会出现一道测试问题，答对了一道题就允许成功入群了，而不能实现对已定义的问题全部进行测试，必须答对多道问题后才允许入群。

**Comment by Hentioe** [comment]
你说的这个曾经在另一个机器人上实现过，这个暂时没有。但这也是计划中的功能（多阶段验证），不过还没有安排明确的开发时间。

**Comment by toaoman** [comment]
请问你说的这个能实现多阶段验证的机器人是哪一个项目？或者是哪一个机器人？能推荐学习一下吗？

**Comment by Hentioe** [comment]
已经停运了。没啥推荐学习的，这不是很简单的功能么。
