### ISSUE TITLE
无法上传图片验证资源

### ISSUE THREAD

**Issue by ThekingMX1998** [Hentioe/policr-mini#174]
打包完成的 _albums.zip 无法上传

-------------------------------------

![UPLOAD](https://user-images.githubusercontent.com/79040577/202881358-69e030de-1608-451e-9a4f-a953159c3475.png)

**后台log:**
![LOGS](https://user-images.githubusercontent.com/79040577/202881409-90ca6108-2338-4735-85a1-745dda475259.png)

**Docker log:**
```
15:18:19.524 request_id=FykFbEcYiKMz8-kAAADC [info] POST /admin/api/profile/temp_albums
15:18:19.532 request_id=FykFbEcYiKMz8-kAAADC [info] Sent 400 in 7ms
15:18:50.271 request_id=FykFc2--F0W5MDIAAADi [info] POST /admin/api/profile/temp_albums
15:18:50.276 request_id=FykFc2--F0W5MDIAAADi [info] Sent 400 in 4ms
15:19:21.483 request_id=FykFerQbddsrDs4AAADy [info] POST /admin/api/profile/temp_albums
15:19:21.488 request_id=FykFerQbddsrDs4AAADy [info] Sent 400 in 5ms 
```

[_albums.zip](https://github.com/Hentioe/policr-mini/files/10048396/_albums.zip)

**操作系统:** Debian 10.2.1-6

**Docker Version:** 20.10.17

**Comment by Hentioe** [comment]
您是否有通过 nginx 反代？

**Comment by ThekingMX1998** [comment]
是的 但我使用未反代的 ip+端口 也无法上传

**Comment by Hentioe** [comment]
有空我会尝试重现一下

**Comment by Hentioe** [comment]
哦，对了。在无法成功上传的情况下，可以进入部署 policr-mini 的主目录，会看到 `_assets` 目录，在里边创建 `_albums` 目录，然后把你的压缩包解压文件全部放进去。注意，`_albums` 目录里边是一个个图片的分类文件夹，也包含 `Manifest.yaml` 文件。
做完这些后用 `docker-compose restart` 命令重启机器人即可。

**Comment by ThekingMX1998** [comment]
好的
