### ISSUE TITLE
[Bug]: 英文消息格式化失败

### ISSUE THREAD

**Issue by omg-xtao** [Hentioe/policr-mini#182]
# Commit

[`b3f7ffa55aca0569b17007ca62a803f2d9f9d578`](https://github.com/Hentioe/policr-mini/commit/b3f7ffa55aca0569b17007ca62a803f2d9f9d578)

# 运行环境

Docker

# 日志记录

```
[error] Send message failed: [text: "*Synchronization successful*\n\n✔️ Group information has been updated.\n✔️ Administrator permissions have been updated.\n✔️ The new member verification is already in takeover mode.\n", reason: %Telegex.Model.Error{description: "Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\\'", error_code: 400}]
```

**Comment by Hentioe** [comment]
应该跟你贴出来的 commit 无关。后面的版本已经移除了内置的日志查看功能，你这个日志是从控制台看到的吗？

**Comment by omg-xtao** [comment]
commit 只是说明是最新版本，日志是通过 docker logs 查看的

**Comment by Hentioe** [comment]
这个错误应该是响应 `/sync` 命令时产生的，原因和文字格式有关。虽然源代码中已经基本包含完整的英文翻译了，但实际上并没有启用英文。你是如何获得英文响应的呢？修改过源代码吗还是？（如果没有，这可能是一个 bug）

**Comment by omg-xtao** [comment]
没有呀，我从旧版本升级 docker 就是英文了

**Comment by Hentioe** [comment]
这应该是一个 bug，我很快会确认并修复。

**Comment by Hentioe** [comment]
感谢反馈，问题已经修复了，并已推送到 develop 分支镜像。现在默认会是中文，英文在没提供语言修改入口前不会再启用。
