### ISSUE TITLE
Unknown value of variable POLICR_MINI_UNBAN_METHOD

### ISSUE THREAD

**Issue by Deniel-nice** [Hentioe/policr-mini#187]
docker compose logs server查看日志报错如下，但是后来我在配置文件中加入了POLICR_MINI_UNBAN_METHOD=until_date，也重新执行了docker compose up -d依旧报错：
还请大佬帮忙看一下是怎么回事

server-1  | init terminating in do_boot ({,[{erl_eval,do_apply,6,[{_},{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]},{Elixir.Config.Reader,load,2,[{_},{_}]}]})
server-1  | ERROR! Config provider Config.Reader failed with:
server-1  | ** (RuntimeError) Unknown value of variable POLICR_MINI_UNBAN_METHOD: 
server-1  | 
server-1  |     (stdlib 3.17.2) erl_eval.erl:685: :erl_eval.do_apply/6
server-1  |     (stdlib 3.17.2) erl_eval.erl:446: :erl_eval.expr/5
server-1  |     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
server-1  |     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
server-1  |     (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
server-1  |     (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
server-1  |     (elixir 1.13.4) lib/config/reader.ex:92: Config.Reader.read!/2
server-1  |     (elixir 1.13.4) lib/config/reader.ex:58: Config.Reader.load/2
server-1  | 
server-1  | 
server-1  | Crash dump is being written to: erl_crash.dump...done

**Comment by Deniel-nice** [comment]
感谢回复，我刚重新配置了一下，使用的最新的镜像和教程，成功了

**Comment by Deniel-nice** [comment]
请问大佬，这边跑起来了，如何让TG那边的机器人使用验证功能呢，我跑起来但是TG机器人没反应，还是不验证

**Comment by Deniel-nice** [comment]
server-1  | 06:45:57.503 request_id=F7fz5xmBiAuRdYUAACph [info] Sent 200 in 2ms
server-1  | 06:46:16.326 [warning] Getting updates failed: %Telegex.RequestError{reason: :timeout}
server-1  | 06:46:24.365 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:46:32.402 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:46:40.440 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:47:06.194 [warning] Getting updates failed: %Telegex.RequestError{reason: :timeout}
server-1  | 06:47:14.232 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:47:22.269 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:47:30.306 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:47:38.344 [warning] Getting updates failed: %Telegex.RequestError{reason: :nxdomain}
server-1  | 06:48:33.085 request_id=F7f0C1MRAvI8vb8AACpx [info] GET /api/index
server-1  | 06:48:33.086 request_id=F7f0C1Mcjx4tAgYAACqB [info] GET /api/sponsorship_histories
server-1  | 06:48:33.087 request_id=F7f0C1MRAvI8vb8AACpx [info] Sent 200 in 1ms
server-1  | 06:48:33.091 request_id=F7f0C1Mcjx4tAgYAACqB [info] Sent 200 in 5ms
server-1  | 06:48:53.800 request_id=F7f0ECXEJUr9tOAAACqR [info] GET /api/index
server-1  | 06:48:53.801 request_id=F7f0ECXEJUr9tOAAACqR [info] Sent 200 in 415µs
server-1  | 06:48:53.802 request_id=F7f0ECXeF9Elv1oAACqh [info] GET /api/sponsorship_histories
server-1  | 06:48:53.804 request_id=F7f0ECXeF9Elv1oAACqh [info] Sent 200 in 1ms
server-1  | 06:49:19.037 request_id=F7f0FgYE7ehuoNkAACqx [info] GET /api/index
server-1  | 06:49:19.038 request_id=F7f0FgYE7ehuoNkAACqx [info] Sent 200 in 695µs
server-1  | 06:49:19.040 request_id=F7f0FgYmDqK5TCYAACrB [info] GET /api/sponsorship_histories
server-1  | 06:49:19.041 request_id=F7f0FgYmDqK5TCYAACrB [info] Sent 200 in 1ms
server-1  | 06:49:56.743 request_id=F7f0Hs1qvD7nqSoAACrR [info] GET /api/index
server-1  | 06:49:56.743 request_id=F7f0Hs1qvD7nqSoAACrR [info] Sent 200 in 639µs
server-1  | 06:49:56.746 request_id=F7f0Hs2eBkOAiXkAACrh [info] GET /api/sponsorship_histories
server-1  | 06:49:56.749 request_id=F7f0Hs2eBkOAiXkAACrh [info] Sent 200 in 2ms
server-1  | 06:51:07.162 request_id=F7f0LzK84FqKIdoAACrx [info] GET /api/sponsorship_histories
server-1  | 06:51:07.166 request_id=F7f0LzK84FqKIdoAACrx [info] Sent 200 in 3ms
server-1  | 06:51:07.169 request_id=F7f0LzMluH_-MjcAACsB [info] GET /api/index
server-1  | 06:51:07.169 request_id=F7f0LzMluH_-MjcAACsB [info] Sent 200 in 182µs



这是日志信息，表示域名不存在，但是没懂，到底哪会涉及到这个问题

**Comment by Deniel-nice** [comment]
server-1  | 02:37:28.618 [info] Running PolicrMiniWeb.Endpoint with cowboy 2.10.0 at :::8080 (http)
server-1  | 02:37:28.619 [info] Access PolicrMiniWeb.Endpoint at http://localhost:8080
server-1  | 02:37:29.546 [info] Image provider started
server-1  | 02:37:29.546 [info] Checking bot information...
server-1  | 02:37:30.420 [info] Bot (@beef_noodles_bot) is working (polling)
server-1  | 02:37:30.420 [info] Updates poller started
server-1  | 02:37:38.770 request_id=F7g07slIR_9m0mQAABzR [info] GET //
server-1  | 02:37:38.771 request_id=F7g07slIR_9m0mQAABzR [info] Sent 200 in 285µs
server-1  | 02:37:39.757 request_id=F7g07wQXQ-c7WXoAABzh [info] GET /api/sponsorship_histories
server-1  | 02:37:39.759 request_id=F7g07wQt0Lghna8AAB0B [info] GET /api/index
server-1  | 02:37:39.759 request_id=F7g07wQt0Lghna8AAB0B [info] Sent 200 in 157µs
server-1  | 02:37:39.760 request_id=F7g07wQXQ-c7WXoAABzh [info] Sent 200 in 3ms
server-1  | 02:37:39.960 request_id=F7g07xA180iRZjcAAB0h [info] GET /own_photo
server-1  | 02:37:39.961 request_id=F7g07xA180iRZjcAAB0h [info] Sent 302 in 154µs
server-1  | 02:37:48.384 request_id=F7g08QZDzHYEe4MAAB0x [info] GET /
server-1  | 02:37:48.384 request_id=F7g08QZDzHYEe4MAAB0x [info] Sent 200 in 238µs
server-1  | 02:38:53.425 request_id=F7g1ACsIrW37BzMAAB1B [info] GET /api/index
server-1  | 02:38:53.425 request_id=F7g1ACsIrW37BzMAAB1B [info] Sent 200 in 272µs
server-1  | 02:38:53.433 request_id=F7g1ACuDuUxVjjUAAB1R [info] GET /api/sponsorship_histories
server-1  | 02:38:53.435 request_id=F7g1ACuDuUxVjjUAAB1R [info] Sent 200 in 2ms
server-1  | 02:41:31.756 request_id=F7g1JQhIFjOk_yEAAB2B [info] GET /api/index
server-1  | 02:41:31.756 request_id=F7g1JQhIFjOk_yEAAB2B [info] Sent 200 in 269µs
server-1  | 02:41:31.839 request_id=F7g1JQ05iZJk8H8AAB2R [info] GET /api/sponsorship_histories
server-1  | 02:41:31.841 request_id=F7g1JQ05iZJk8H8AAB2R [info] Sent 200 in 2ms
server-1  | 02:42:09.051 request_id=F7g1Lbc7lzS7SicAAB2h [info] GET /api/index
server-1  | 02:42:09.051 request_id=F7g1Lbc7lzS7SicAAB2h [info] Sent 200 in 254µs
server-1  | 02:42:09.052 request_id=F7g1LbdPovPXoNUAAB2x [info] GET /api/sponsorship_histories
server-1  | 02:42:09.054 request_id=F7g1LbdPovPXoNUAAB2x [info] Sent 200 in 1ms


真奇怪，我又重新来了一边，没有报错了，但是TG机器人还是没有反应，另外就是我的服务器ip是德国的，不在中国境内，真的很奇葩

**Comment by Hentioe** [comment]
应该是机器人没有记录你的群数据，你在群里发送 `/sync` 命令后，再试试。

**Comment by Deniel-nice** [comment]
目前这个机器人可以实现删除进群退群消息吗

**Comment by Deniel-nice** [comment]
我记得我一年前使用的时候是没有删除进群退群消息的

**Comment by Deniel-nice** [comment]
我记得我一年前使用的时候好像是没有删除进群退群消息的

**Comment by Deniel-nice** [comment]
目前这个机器人是否是只能删除用户进群退群的消息，但是无法删除机器人踢出群的消息呀 大佬

**Comment by Hentioe** [comment]
用电脑浏览器进入后台 有相关设置 把服务消息全部选上就行 其余的有使用问题请在群里问吧 我看到会回复的 这个 issue 我关掉了。
