### ISSUE TITLE
能添加一个本地启动教程吗？

### ISSUE THREAD

**Issue by ray1888** [Hentioe/policr-mini#22]
因为我本地启动了pg 的docker之后还是没成功拉起来，不知道确定是否是npm 那边的build的问题（不太熟悉npm的操作）

**Comment by Hentioe** [comment]
不关 npm 什么事儿，这不是 nodejs 项目。你先要了解一下 elixir 的入门知识。

**Comment by Hentioe** [comment]
如果你是想自己部署，我可以告诉你怎么部署，不需要 npm 和 elixir 相关知识。如果你是想参与开发，你得学习 elixir 这门语言。

请告诉我你的目的。

**Comment by ray1888** [comment]
我是后者，是想学elixir，然后顺便找个项目可以练手

**Comment by Hentioe** [comment]
那你可以来我的群交流一下：https://t.me/elixir_cn

**Comment by ray1888** [comment]
已经加了，之前还问过hex的代理问题
