### ISSUE TITLE
操作记录设计

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/policr-mini#95]
当机器人通过验证记录对用户进行「封禁」和「踢出」两个动作时将产生操作记录，此记录可通过后台查阅。

操作记录应包含：

- 验证记录 ID（外键，多对一关系）
- 执行动作
- 操作人角色

操作人角色初步分为「系统」和「管理员」。系统表示验证超时或错误导致的机器人主动操作。管理员表示有后台操作权限的人通过验证记录列表手动实施的操作。

**Comment by steamsv** [comment]
@Hentioe 在路上
